# Generated by Django 4.2.26 on 2026-08-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employeeprofile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
