# Generated by Django 6.1 on 2026-09-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employeeprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
