# Generated by Django 6.1 on 2026-09-03 11:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appbuild',
            name='build_file',
        ),
        migrations.AddField(
            model_name='appbuild',
            name='download_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
